import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"], weight: ["300"],
});

export const metadata: Metadata = {
  title: "Image Lite App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className + " bg-gray-100 min-h-screen"}
      >
        {children}
      </body>
    </html>
  );
}
